#!/usr/bin/env ruby
require 'bin_install'

APP_ROOT = File.expand_path('..', __dir__)

Dir.chdir(APP_ROOT) do
  BinInstall::Brew.require!
  BinInstall::OhMyZsh.install
  BinInstall::Ruby.install
  BinInstall::Postgres.install
  BinInstall::Postgres.create_superuser('postgres')
  BinInstall::Gem.install!
  BinInstall::Git.install
  BinInstall::Node.install
  BinInstall::Yarn.install
  BinInstall::Redis.install
  BinInstall::Rails.db_setup
  BinInstall::Rails.clear
end
