#!/usr/bin/env ruby
require 'bin_install'

APP_ROOT = File.expand_path('..', __dir__)

Dir.chdir(APP_ROOT) do
  BinInstall::Gem.install!
  BinInstall::Yarn.install
  BinInstall::Rails.db_migrate
  BinInstall::Rails.clear
end
